export const searchKeywords = [
  "Pants",
  "Shirt",
  "Co-ords",
  "Denims",
  "Party wear",
  "Summer chic",
  "Shirt dress",
  "Knits",
  "Bodycon dress",
  "Oversized t-shirt",
  "Crop top",
  "Blazer set",
  "Printed co-ords",
  "Satin dress",
  "Wrap dress",
  "Wide leg pants",
  "Jumpsuit",
  "Mini dress",
  "Maxi dress",
  "Bomber jacket",
  "Graphic t-shirt",
  "Pleated skirt",
  "Leather pants",
  "Tube top",
  "Cargo pants",
  "Mesh top",
];
